### PR TITLE
Refactor app coin

### PR DESCRIPTION
**Pull request by boqiu**
1. Decouple app coins, settlement and api config.
2. Leverage standard `AccessControl` for privilege management.
3. Added necessary **TODO** for further PRs.

- - -
This change is [Reviewable](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41)

### CODE REVIEW

**Review by Tigo9527 — APPROVED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41)* status: all files reviewed, 5 unresolved discussions (waiting on @boqiu)

___
*[`contracts/v2/App.sol` line 16 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUgoKn-42GZbi0UMtE:-NCUgoKn-42GZbi0UMtF:b-oeqdqc) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L16)):*
> ```Solidity
>     event Deposit(address indexed operator, address indexed receiver, uint256 amount);
>     event Airdrop(address indexed operator, address indexed receiver, uint256 amount, string reason);
> ```

It can be detected off-chain via the Transfer event. The specified event is redundant.
___
*[`contracts/v2/App.sol` line 40 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUgZNE4ZfOL_Y0Kjt3:-NCUgZNE4ZfOL_Y0Kjt4:b-epydm7) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L40)):*
> ```Solidity
>      * The 1st amount is from user deposit, and the 2nd amount is from airdrop.
>      */
>     function balanceOf(address account) public view returns (uint256, uint256) {
> ```

Maybe it can be done using multi-call on the front end.
___
*[`contracts/v2/App.sol` line 79 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUhRbhA5iTiOh4h4So:-NCUhRbhA5iTiOh4h4Sp:b-yq2ytp) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L79)):*
> ```Solidity
>             vipCoin.mint(receivers[i], TOKEN_ID_AIRDROP, amounts[i], "");
>             emit Airdrop(_msgSender(), receivers[i], amounts[i], reasons[i]);
>         }
> ```

Emit batch event?
___
*[`contracts/v2/SwapExchange.sol` line 38 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUd_hR5NTMdDiYfqws:-NCUd_hR5NTMdDiYfqwt:bb7phvt) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/SwapExchange.sol#L38)):*
> ```Solidity
>  * @dev SwapExchage is used to deposit/withdraw App Coins based on native tokens.
>  */
> contract SwapExchage is ReentrancyGuard {
> ```

typo



_Code quote:_
```Solidity
SwapExchage
```
___
*[`contracts/v2/VipCoin.sol` line 34 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUercgA3z_MfGlIQZB:-NCUerch2JTtrYp0TbZq:b71busi) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/VipCoin.sol#L34)):*
> ```Solidity
>         uint256 value
>     ) public virtual override {
>         if (hasRole(CONSUMER_ROLE, _msgSender())) {
> ```

Duplicate with permission checking in _beforeTokenTransfer.

**Review by boqiu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @Tigo9527)

___
*[`contracts/v2/App.sol` line 16 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUgoKn-42GZbi0UMtE:-NCXwAbL1IkZJ-SotCus:b-54zb35) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L16)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

It can be detected off-chain via the Transfer event. The specified event is redundant.
</blockquote></details>

Above 2 events are different from the standard `Transfer` event. The `operator` is not zero address, instead, it is the transaction sender to indicate who deposit with APP Coin. On the other hand, I followed your previous `Drop` event that add a `reason` for airdrops.
___
*[`contracts/v2/App.sol` line 40 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUgZNE4ZfOL_Y0Kjt3:-NCXxNbJ7lob9WgBYjFP:b-g7447x) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L40)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Maybe it can be done using multi-call on the front end.
</blockquote></details>

Yes, client could call `VipCoin.balanceOf` directly. However, this method allow users to not aware the exact token id for quota and airdrops.
___
*[`contracts/v2/App.sol` line 79 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUhRbhA5iTiOh4h4So:-NCXyBU296XxAJ1XxIdj:b-ndy4lv) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L79)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Emit batch event?
</blockquote></details>

How to define the parameters within a batch event?
___
*[`contracts/v2/SwapExchange.sol` line 38 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUd_hR5NTMdDiYfqws:-NCXyvgg9ZrFAfoXhkV4:bb6un1j) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/SwapExchange.sol#L38)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done
___
*[`contracts/v2/VipCoin.sol` line 34 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUercgA3z_MfGlIQZB:-NCXyhJv-jI5mVoWEjJd:b-c83poa) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/VipCoin.sol#L34)):*
<details><summary><i>Previously, Tigo9527 wrote…</i></summary><blockquote>

Duplicate with permission checking in _beforeTokenTransfer.
</blockquote></details>

Only `transfer` case checked in `_beforeTokenTransfer`.

**Review by Tigo9527 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> Dismissed @boqiu from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

**Review by Tigo9527 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

___
*[`contracts/v2/App.sol` line 16 at r1](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41#-NCUgoKn-42GZbi0UMtE:-NCY2FvF313QNNIGaW6k:b-m5ul6d) ([raw file](https://github.com/conflux-chain/web3pay-contract/blob/94b74890c577e5352ff3e6a533f361a9efe69485/contracts/v2/App.sol#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Above 2 events are different from the standard `Transfer` event. The `operator` is not zero address, instead, it is the transaction sender to indicate who deposit with APP Coin. On the other hand, I followed your previous `Drop` event that add a `reason` for airdrops.
</blockquote></details>

Consider removing.

**Review by Tigo9527 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/conflux-chain/web3pay-contract/41)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @boqiu)

**Pull request merged**
